-- =====================================================================
-- Plataforma de Gestión de Donación de Órganos — Esquema relacional
-- Motor: PostgreSQL (Neon)
-- Autor: DidierParody (encargado de base de datos)
--
-- Qué hace: define el modelo relacional completo del MVP en dos esquemas
-- lógicos alineados a los dos backends Spring Boot:
--   - auth : autenticación y usuarios            (Backend 1)
--   - core : donantes, receptores y procesos     (Backend 2)
-- Las imágenes/documentos NO se guardan en la DB: solo se almacena la ruta
-- al archivo en uploads/ del backend (columnas *_path).
--
-- NOTA: la fuente EJECUTABLE de verdad es la migración Flyway
--   backend/auth-service/src/main/resources/db/migration/V1__init_schema.sql
-- Este archivo es documentación de referencia y debe mantenerse en sincronía.
-- Los ENUM se representan como VARCHAR + CHECK (mapeo limpio con JPA @Enumerated(STRING)
-- y ddl-auto=validate).
-- =====================================================================

-- ----- Esquemas --------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS core;

-- =====================================================================
-- ESQUEMA auth (Backend 1: autenticación + usuarios)
-- =====================================================================

-- Cuenta de acceso de cualquier rol del sistema (médico, donante, receptor).
CREATE TABLE auth.users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(12)  NOT NULL CHECK (role IN ('MEDICO','DONANTE','RECEPTOR')),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Perfil del profesional de salud (médico administrador). Incluye los campos
-- de verificación RETHUS; el FLUJO de verificación queda PENDIENTE de decisión
-- del equipo, pero el modelo ya lo soporta.
CREATE TABLE auth.medical_professional_profiles (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT NOT NULL UNIQUE
                                    REFERENCES auth.users(id) ON DELETE CASCADE,
    full_name                   VARCHAR(150) NOT NULL,
    document_type               VARCHAR(20)  NOT NULL,
    document_number             VARCHAR(40)  NOT NULL UNIQUE,
    rethus_registration_number  VARCHAR(60),
    professional_profile        VARCHAR(120),
    verification_status         VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE'
                                    CHECK (verification_status IN ('PENDIENTE','VERIFICADO','RECHAZADO')),
    certificate_file_path       VARCHAR(500),                 -- ruta en uploads/certificates/
    verified_by                 BIGINT REFERENCES auth.users(id) ON DELETE SET NULL,
    verified_at                 TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- ESQUEMA core (Backend 2: donantes, receptores, procesos)
-- =====================================================================

-- Donante registrado por un médico.
CREATE TABLE core.donors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_by   BIGINT NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    document_type   VARCHAR(20)  NOT NULL,
    document_number VARCHAR(40)  NOT NULL UNIQUE,
    full_name       VARCHAR(150) NOT NULL,
    birth_date      DATE,
    sex             VARCHAR(20),
    blood_type      VARCHAR(6) CHECK (blood_type IN
                        ('A_POS','A_NEG','B_POS','B_NEG','AB_POS','AB_NEG','O_POS','O_NEG')),
    contact_phone   VARCHAR(40),
    contact_email   VARCHAR(255),
    address         VARCHAR(255),
    photo_path      VARCHAR(500),                              -- ruta en uploads/donors/
    status          VARCHAR(14) NOT NULL DEFAULT 'EN_EVALUACION'
                        CHECK (status IN ('ACTIVO','EN_EVALUACION','INACTIVO')),
    medical_notes   TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Órganos ofrecidos por un donante (1 donante : N órganos).
CREATE TABLE core.donor_organs (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id  BIGINT NOT NULL REFERENCES core.donors(id) ON DELETE CASCADE,
    organ     VARCHAR(12) NOT NULL CHECK (organ IN
                  ('RINON','HIGADO','CORAZON','PULMON','PANCREAS','CORNEA','INTESTINO','TEJIDO')),
    UNIQUE (donor_id, organ)
);

-- Paciente receptor registrado por un médico.
CREATE TABLE core.recipients (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registered_by   BIGINT NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    document_type   VARCHAR(20)  NOT NULL,
    document_number VARCHAR(40)  NOT NULL UNIQUE,
    full_name       VARCHAR(150) NOT NULL,
    birth_date      DATE,
    sex             VARCHAR(20),
    blood_type      VARCHAR(6) CHECK (blood_type IN
                        ('A_POS','A_NEG','B_POS','B_NEG','AB_POS','AB_NEG','O_POS','O_NEG')),
    organ_needed    VARCHAR(12) CHECK (organ_needed IN
                        ('RINON','HIGADO','CORAZON','PULMON','PANCREAS','CORNEA','INTESTINO','TEJIDO')),
    urgency_level   VARCHAR(8) NOT NULL DEFAULT 'MEDIA'
                        CHECK (urgency_level IN ('BAJA','MEDIA','ALTA','CRITICA')),
    contact_phone   VARCHAR(40),
    contact_email   VARCHAR(255),
    photo_path      VARCHAR(500),                              -- ruta en uploads/recipients/
    status          VARCHAR(14) NOT NULL DEFAULT 'EN_ESPERA'
                        CHECK (status IN ('EN_ESPERA','EN_EVALUACION','TRASPLANTADO','INACTIVO')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Proceso/caso de donación que vincula a un donante y/o un receptor.
CREATE TABLE core.donation_processes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id      BIGINT REFERENCES core.donors(id)     ON DELETE SET NULL,
    recipient_id  BIGINT REFERENCES core.recipients(id) ON DELETE SET NULL,
    current_state VARCHAR(20) NOT NULL DEFAULT 'REGISTRADO'
                      CHECK (current_state IN ('REGISTRADO','EN_EVALUACION','EN_ESPERA',
                          'MATCH_ENCONTRADO','EN_PROCESO_CLINICO','COMPLETADO','CANCELADO')),
    opened_by     BIGINT NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Historial de cambios de estado del proceso (trazabilidad — HU-09, HU-10).
-- Cada cambio puede llevar una observación clínica.
CREATE TABLE core.process_status_history (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id          BIGINT NOT NULL REFERENCES core.donation_processes(id) ON DELETE CASCADE,
    previous_state      VARCHAR(20) CHECK (previous_state IN ('REGISTRADO','EN_EVALUACION','EN_ESPERA',
                            'MATCH_ENCONTRADO','EN_PROCESO_CLINICO','COMPLETADO','CANCELADO')),
    new_state           VARCHAR(20) NOT NULL CHECK (new_state IN ('REGISTRADO','EN_EVALUACION','EN_ESPERA',
                            'MATCH_ENCONTRADO','EN_PROCESO_CLINICO','COMPLETADO','CANCELADO')),
    clinical_observation TEXT,
    changed_by          BIGINT NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    changed_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Documentos/archivos clínicos adjuntos a un proceso (solo la ruta, no el binario).
CREATE TABLE core.process_documents (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_id    BIGINT NOT NULL REFERENCES core.donation_processes(id) ON DELETE CASCADE,
    file_path     VARCHAR(500) NOT NULL,                       -- ruta en uploads/
    original_name VARCHAR(255),
    mime_type     VARCHAR(120),
    size_bytes    BIGINT,
    uploaded_by   BIGINT NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    uploaded_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Reportes clínicos de un receptor, redactados por un médico.
-- El paciente es un receptor (core.recipients), NO un usuario que inicia sesión.
CREATE TABLE core.medical_reports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES core.recipients(id) ON DELETE CASCADE,
    doctor_id    BIGINT NOT NULL REFERENCES auth.users(id)      ON DELETE RESTRICT,
    description  TEXT NOT NULL,
    diagnosis    TEXT,
    report_date  DATE NOT NULL,
    status       VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE'
                     CHECK (status IN ('PENDIENTE','COMPLETADO','EN_REVISION')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----- Índices de apoyo (consultas frecuentes / dashboard) -------------
CREATE INDEX idx_donors_status            ON core.donors(status);
CREATE INDEX idx_donors_registered_by     ON core.donors(registered_by);
CREATE INDEX idx_recipients_status        ON core.recipients(status);
CREATE INDEX idx_recipients_organ_needed  ON core.recipients(organ_needed);
CREATE INDEX idx_processes_current_state  ON core.donation_processes(current_state);
CREATE INDEX idx_processes_donor          ON core.donation_processes(donor_id);
CREATE INDEX idx_processes_recipient      ON core.donation_processes(recipient_id);
CREATE INDEX idx_history_process          ON core.process_status_history(process_id);
CREATE INDEX idx_profiles_verification    ON auth.medical_professional_profiles(verification_status);
CREATE INDEX idx_medreports_recipient     ON core.medical_reports(recipient_id);
CREATE INDEX idx_medreports_doctor        ON core.medical_reports(doctor_id);
CREATE INDEX idx_medreports_status        ON core.medical_reports(status);

-- ----- Integridad: registered_by debe ser un usuario con rol MEDICO ----
-- Patrón de FK compuesta a un subconjunto (sin triggers): una columna
-- generada fija 'MEDICO' + FK hacia auth.users(id, role) garantiza, a nivel
-- de base de datos, que solo un médico pueda figurar como quien registró un
-- donante o un receptor (ningún otro rol puede registrarlos).
ALTER TABLE auth.users ADD CONSTRAINT users_id_role_uk UNIQUE (id, role);

ALTER TABLE core.donors
    ADD COLUMN registered_by_role VARCHAR(12) GENERATED ALWAYS AS ('MEDICO') STORED;
ALTER TABLE core.donors
    ADD CONSTRAINT donors_registered_by_medico_fk
        FOREIGN KEY (registered_by, registered_by_role)
        REFERENCES auth.users(id, role) ON DELETE RESTRICT;

ALTER TABLE core.recipients
    ADD COLUMN registered_by_role VARCHAR(12) GENERATED ALWAYS AS ('MEDICO') STORED;
ALTER TABLE core.recipients
    ADD CONSTRAINT recipients_registered_by_medico_fk
        FOREIGN KEY (registered_by, registered_by_role)
        REFERENCES auth.users(id, role) ON DELETE RESTRICT;
