-- =====================================================================
-- Datos de prueba (DEV) — Plataforma de Donación de Órganos
-- Motor: PostgreSQL (Neon). Pensado SOLO para desarrollo/demo.
--
-- ⚠️ Este script BORRA los datos existentes de auth/core y los recrea.
--    NO ejecutar en un entorno con datos reales.
-- ⚠️ NO es una migración Flyway (no va en db/migration): se corre a mano.
--
-- Usa búsquedas por email / número de documento (no IDs fijos) para ser
-- robusto ante los IDs autogenerados (GENERATED BY DEFAULT AS IDENTITY).
-- =====================================================================

BEGIN;

-- ----- Limpieza (orden seguro por FKs) --------------------------------
DELETE FROM core.medical_reports;
DELETE FROM core.process_documents;
DELETE FROM core.process_status_history;
DELETE FROM core.donation_processes;
DELETE FROM core.donor_organs;
DELETE FROM core.recipients;
DELETE FROM core.donors;
DELETE FROM auth.medical_professional_profiles;
DELETE FROM auth.users;

-- ----- Usuarios (auth.users) ------------------------------------------
-- NOTA: password_hash es un valor DUMMY (no es un hash real). El registro
-- actual guarda texto plano; cuando se añada BCrypt + login, reemplazar.
INSERT INTO auth.users (email, password_hash, role, is_active) VALUES
    ('carla.medico@hospital.co',  'dummy-hash-carla',  'MEDICO',   TRUE),
    ('jorge.medico@hospital.co',  'dummy-hash-jorge',  'MEDICO',   TRUE),
    ('ana.donante@mail.co',       'dummy-hash-ana',    'DONANTE',  TRUE),
    ('luis.donante@mail.co',      'dummy-hash-luis',   'DONANTE',  TRUE),
    ('marta.receptor@mail.co',    'dummy-hash-marta',  'RECEPTOR', TRUE),
    ('pedro.receptor@mail.co',    'dummy-hash-pedro',  'RECEPTOR', FALSE);

-- ----- Perfiles de médico (auth.medical_professional_profiles) --------
INSERT INTO auth.medical_professional_profiles
    (user_id, full_name, document_type, document_number, rethus_registration_number,
     professional_profile, verification_status, certificate_file_path, verified_by, verified_at)
VALUES
    ((SELECT id FROM auth.users WHERE email='carla.medico@hospital.co'),
     'Carla Restrepo Gómez', 'CC', '1010101010', 'RM-12345',
     'Medicina - Nefrología', 'VERIFICADO', 'uploads/certificates/carla.pdf', NULL, now()),
    ((SELECT id FROM auth.users WHERE email='jorge.medico@hospital.co'),
     'Jorge Patiño Ruiz', 'CC', '1020304050', 'RM-67890',
     'Medicina - Cirugía de Trasplantes', 'PENDIENTE', NULL, NULL, NULL);

-- ----- Donantes (core.donors), registrados por Carla ------------------
INSERT INTO core.donors
    (registered_by, document_type, document_number, full_name, birth_date, sex,
     blood_type, contact_phone, contact_email, address, photo_path, status, medical_notes)
VALUES
    ((SELECT id FROM auth.users WHERE email='carla.medico@hospital.co'),
     'CC', '2020202020', 'Ana María López', '1990-04-12', 'F',
     'O_POS', '3001112233', 'ana.donante@mail.co', 'Cra 10 # 20-30, Bogotá',
     'uploads/donors/ana.jpg', 'ACTIVO', 'Donante en buen estado general.'),
    ((SELECT id FROM auth.users WHERE email='carla.medico@hospital.co'),
     'CC', '2021212121', 'Luis Fernando Díaz', '1985-11-02', 'M',
     'A_POS', '3004445566', 'luis.donante@mail.co', 'Calle 45 # 12-08, Medellín',
     NULL, 'EN_EVALUACION', 'Pendiente de exámenes complementarios.');

-- ----- Órganos ofrecidos (core.donor_organs) --------------------------
INSERT INTO core.donor_organs (donor_id, organ) VALUES
    ((SELECT id FROM core.donors WHERE document_number='2020202020'), 'RINON'),
    ((SELECT id FROM core.donors WHERE document_number='2020202020'), 'HIGADO'),
    ((SELECT id FROM core.donors WHERE document_number='2021212121'), 'CORNEA');

-- ----- Receptores (core.recipients), registrados por Jorge ------------
INSERT INTO core.recipients
    (registered_by, document_type, document_number, full_name, birth_date, sex,
     blood_type, organ_needed, urgency_level, contact_phone, contact_email, photo_path, status)
VALUES
    ((SELECT id FROM auth.users WHERE email='jorge.medico@hospital.co'),
     'CC', '3030303030', 'Marta Sánchez Peña', '1978-07-21', 'F',
     'O_POS', 'RINON', 'ALTA', '3017778899', 'marta.receptor@mail.co',
     'uploads/recipients/marta.jpg', 'EN_ESPERA'),
    ((SELECT id FROM auth.users WHERE email='jorge.medico@hospital.co'),
     'CC', '3031313131', 'Pedro Gaitán Mora', '1965-01-30', 'M',
     'A_POS', 'HIGADO', 'CRITICA', '3018889900', 'pedro.receptor@mail.co',
     NULL, 'EN_EVALUACION');

-- ----- Procesos de donación (core.donation_processes), abiertos por Carla
INSERT INTO core.donation_processes (donor_id, recipient_id, current_state, opened_by) VALUES
    ((SELECT id FROM core.donors     WHERE document_number='2020202020'),
     (SELECT id FROM core.recipients WHERE document_number='3030303030'),
     'MATCH_ENCONTRADO',
     (SELECT id FROM auth.users WHERE email='carla.medico@hospital.co')),
    ((SELECT id FROM core.donors WHERE document_number='2021212121'),
     NULL,
     'EN_EVALUACION',
     (SELECT id FROM auth.users WHERE email='carla.medico@hospital.co'));

-- ----- Historial de estados (core.process_status_history) — proceso 1 -
INSERT INTO core.process_status_history
    (process_id, previous_state, new_state, clinical_observation, changed_by)
VALUES
    ((SELECT id FROM core.donation_processes
        WHERE donor_id=(SELECT id FROM core.donors WHERE document_number='2020202020')),
     NULL, 'REGISTRADO', 'Apertura del caso de donación.',
     (SELECT id FROM auth.users WHERE email='carla.medico@hospital.co')),
    ((SELECT id FROM core.donation_processes
        WHERE donor_id=(SELECT id FROM core.donors WHERE document_number='2020202020')),
     'REGISTRADO', 'EN_EVALUACION', 'Inicio de evaluación de compatibilidad.',
     (SELECT id FROM auth.users WHERE email='carla.medico@hospital.co')),
    ((SELECT id FROM core.donation_processes
        WHERE donor_id=(SELECT id FROM core.donors WHERE document_number='2020202020')),
     'EN_EVALUACION', 'MATCH_ENCONTRADO', 'Compatibilidad confirmada con receptor.',
     (SELECT id FROM auth.users WHERE email='jorge.medico@hospital.co'));

-- ----- Documentos adjuntos (core.process_documents) — proceso 1 -------
INSERT INTO core.process_documents
    (process_id, file_path, original_name, mime_type, size_bytes, uploaded_by)
VALUES
    ((SELECT id FROM core.donation_processes
        WHERE donor_id=(SELECT id FROM core.donors WHERE document_number='2020202020')),
     'uploads/processes/p1/historia_clinica.pdf', 'historia_clinica.pdf',
     'application/pdf', 245678,
     (SELECT id FROM auth.users WHERE email='carla.medico@hospital.co'));

-- ----- Reportes clínicos (core.medical_reports) — receptor Marta -------
INSERT INTO core.medical_reports
    (recipient_id, doctor_id, description, diagnosis, report_date, status)
VALUES
    ((SELECT id FROM core.recipients WHERE document_number='3030303030'),
     (SELECT id FROM auth.users WHERE email='carla.medico@hospital.co'),
     'Evaluación inicial del receptor.', 'Apto para lista de espera.', CURRENT_DATE, 'COMPLETADO');

COMMIT;
