-- =====================================================================
-- V2 — Columnas adicionales en auth.users + tabla auth.medical_reports
-- Alineado con User.java y MedicalReport.java del auth-service.
-- =====================================================================

-- ─── Nuevas columnas en auth.users ───────────────────────────────────
-- La V1 solo tenía: id, email, password_hash, role, is_active, created_at, updated_at
-- User.java ahora requiere estas columnas adicionales:

ALTER TABLE auth.users
    ADD COLUMN IF NOT EXISTS username        VARCHAR(50)  UNIQUE,
    ADD COLUMN IF NOT EXISTS first_name      VARCHAR(50),
    ADD COLUMN IF NOT EXISTS last_name       VARCHAR(50),
    ADD COLUMN IF NOT EXISTS dni             VARCHAR(20)  UNIQUE,
    ADD COLUMN IF NOT EXISTS birth_date      DATE,
    ADD COLUMN IF NOT EXISTS gender          VARCHAR(10)
                                                 CHECK (gender IN ('MALE','FEMALE','OTHER')),
    ADD COLUMN IF NOT EXISTS blood_type      VARCHAR(11)
                                                 CHECK (blood_type IN (
                                                     'A_POSITIVE','A_NEGATIVE',
                                                     'B_POSITIVE','B_NEGATIVE',
                                                     'AB_POSITIVE','AB_NEGATIVE',
                                                     'O_POSITIVE','O_NEGATIVE')),
    ADD COLUMN IF NOT EXISTS phone           VARCHAR(20),
    ADD COLUMN IF NOT EXISTS address         VARCHAR(200),
    ADD COLUMN IF NOT EXISTS city            VARCHAR(100),
    ADD COLUMN IF NOT EXISTS country         VARCHAR(100) DEFAULT 'Argentina',
    ADD COLUMN IF NOT EXISTS is_donor        BOOLEAN      DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS donor_status    VARCHAR(20)
                                                 CHECK (donor_status IN (
                                                     'REGISTERED','PENDING_APPROVAL',
                                                     'ACTIVE_DONOR','INACTIVE')),
    ADD COLUMN IF NOT EXISTS specialty       VARCHAR(100),
    ADD COLUMN IF NOT EXISTS validation_status VARCHAR(10)
                                                 CHECK (validation_status IN (
                                                     'PENDIENTE','VALIDADO','RECHAZADO'));

-- El CHECK de role en V1 era ('MEDICO','DONANTE','RECEPTOR').
-- User.java ahora admite también 'ADMIN' y 'PACIENTE', así que lo ampliamos:
ALTER TABLE auth.users
    DROP CONSTRAINT IF EXISTS users_role_check;

ALTER TABLE auth.users
    ADD CONSTRAINT users_role_check
        CHECK (role IN ('MEDICO','DONANTE','RECEPTOR','ADMIN','PACIENTE'));

-- ─── Nueva tabla auth.medical_reports ────────────────────────────────
-- Mapeada por MedicalReport.java

CREATE TABLE IF NOT EXISTS auth.medical_reports (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  BIGINT      NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
    doctor_id   BIGINT               REFERENCES auth.users(id) ON DELETE SET NULL,
    description TEXT,
    diagnosis   TEXT,
    report_date DATE        NOT NULL,
    status      VARCHAR(15) NOT NULL DEFAULT 'PENDIENTE'
                    CHECK (status IN ('PENDIENTE','COMPLETADO','EN_REVISION')),
    created_at  TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_medical_reports_patient ON auth.medical_reports(patient_id);
CREATE INDEX IF NOT EXISTS idx_medical_reports_doctor  ON auth.medical_reports(doctor_id);
CREATE INDEX IF NOT EXISTS idx_medical_reports_status  ON auth.medical_reports(status);
