-- =====================================================================
-- V3 — Realineación al modelo canónico
-- Revierte lo que introdujo la V2 y restaura el modelo de datos original:
--   · auth.users vuelve a sus 7 columnas (id, email, password_hash, role,
--     is_active, created_at, updated_at)
--   · roles canónicos: MEDICO, DONANTE, RECEPTOR (se quitan ADMIN/PACIENTE)
--   · los reportes clínicos pasan a core.medical_reports, donde el paciente
--     es un receptor (core.recipients), no un usuario
--   · se refuerza que registered_by sea SIEMPRE un usuario con rol MEDICO
--     (patrón de FK compuesta a un subconjunto, sin triggers)
-- =====================================================================

-- 1. Reportes clínicos al esquema core (paciente = core.recipients) --------
DROP TABLE IF EXISTS auth.medical_reports;

CREATE TABLE IF NOT EXISTS core.medical_reports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES core.recipients(id) ON DELETE CASCADE,
    doctor_id    BIGINT NOT NULL REFERENCES auth.users(id)      ON DELETE RESTRICT,
    description  TEXT NOT NULL,
    diagnosis    TEXT,
    report_date  DATE NOT NULL,
    status       VARCHAR(12) NOT NULL DEFAULT 'PENDIENTE'
                     CHECK (status IN ('PENDIENTE','COMPLETADO','EN_REVISION')),
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_medreports_recipient ON core.medical_reports(recipient_id);
CREATE INDEX IF NOT EXISTS idx_medreports_doctor    ON core.medical_reports(doctor_id);
CREATE INDEX IF NOT EXISTS idx_medreports_status    ON core.medical_reports(status);

-- 2. auth.users vuelve al modelo original de 7 columnas --------------------
ALTER TABLE auth.users
    DROP COLUMN IF EXISTS username,
    DROP COLUMN IF EXISTS first_name,
    DROP COLUMN IF EXISTS last_name,
    DROP COLUMN IF EXISTS dni,
    DROP COLUMN IF EXISTS birth_date,
    DROP COLUMN IF EXISTS gender,
    DROP COLUMN IF EXISTS blood_type,
    DROP COLUMN IF EXISTS phone,
    DROP COLUMN IF EXISTS address,
    DROP COLUMN IF EXISTS city,
    DROP COLUMN IF EXISTS country,
    DROP COLUMN IF EXISTS is_donor,
    DROP COLUMN IF EXISTS donor_status,
    DROP COLUMN IF EXISTS specialty,
    DROP COLUMN IF EXISTS validation_status;

-- 3. Roles canónicos (elimina ADMIN y PACIENTE del CHECK) ------------------
ALTER TABLE auth.users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE auth.users
    ADD CONSTRAINT users_role_check CHECK (role IN ('MEDICO','DONANTE','RECEPTOR'));

-- 4. registered_by debe ser un usuario con rol MEDICO ---------------------
--    Se apoya en una columna generada fija 'MEDICO' + FK compuesta hacia
--    auth.users(id, role). Así la base garantiza que solo un médico puede
--    figurar como quien registró un donante o receptor.
ALTER TABLE auth.users ADD CONSTRAINT users_id_role_uk UNIQUE (id, role);

ALTER TABLE core.donors
    ADD COLUMN IF NOT EXISTS registered_by_role VARCHAR(12) GENERATED ALWAYS AS ('MEDICO') STORED;
ALTER TABLE core.donors
    ADD CONSTRAINT donors_registered_by_medico_fk
        FOREIGN KEY (registered_by, registered_by_role)
        REFERENCES auth.users(id, role) ON DELETE RESTRICT;

ALTER TABLE core.recipients
    ADD COLUMN IF NOT EXISTS registered_by_role VARCHAR(12) GENERATED ALWAYS AS ('MEDICO') STORED;
ALTER TABLE core.recipients
    ADD CONSTRAINT recipients_registered_by_medico_fk
        FOREIGN KEY (registered_by, registered_by_role)
        REFERENCES auth.users(id, role) ON DELETE RESTRICT;

-- 5. Limpieza: historial Flyway duplicado en el esquema public ------------
DROP TABLE IF EXISTS public.flyway_schema_history;
